USE ETL;

SELECT *
FROM cleaned_ecommerce_sales;

#Create SQL Views
#Views store frequently used business queries.

#Total Sales
SELECT SUM(Total) AS Total_Sales
FROM cleaned_ecommerce_sales;
#I calculated total revenue generated by the company.

#Total Orders
SELECT COUNT(*) AS Total_Orders
FROM cleaned_ecommerce_sales; #Company la kalta kiti orders aalya.

#Average Order Value
SELECT AVG(Total) AS Average_Order_Value
FROM cleaned_ecommerce_sales; #Average customer kiti spend karto

#Top selling products 
SELECT Product,
SUM(Total) AS Sales
FROM Cleaned_ecommerce_sales
GROUP BY Product
ORDER BY Sales DESC; #Best selling product identify hotat

#Category Wise Sales
SELECT Category,
SUM(Total) AS Sales
FROM Cleaned_ecommerce_sales
GROUP BY Category
ORDER BY Sales DESC; #konti category jast profit dete

#Monthly Sales
SELECT Month,
SUM(Total) AS Sales
FROM cleaned_ecommerce_sales
GROUP BY Month
ORDER BY Sales DESC; #Seasonality identify hote.

#Payment Method Analysis
SELECT Payment_Method,
COUNT(*) AS Orders
FROM cleaned_ecommerce_sales
GROUP BY Payment_Method; #Most used payment method

#status Analysis
SELECT Status,
COUNT(*) AS Orders
FROM Cleaned_ecommerce_sales
GROUP BY Status; #Delivered vs Cancelled vs Processing

#Customer Type
SELECT
Customer_Type,
COUNT(*) AS Customers
FROM Cleaned_ecommerce_sales
GROUP BY Customer_Type; #preminum customers identify hotat

#Profit
SELECT SUM(Profit) AS Total_profit
FROM Cleaned_ecommerce_sales; #company profit

#Discount
SELECT
SUM(Discount) AS Total_Discount
FROM Cleaned_ecommerce_sales; #company ne kiti discount dila

#Weekend vs Weekday
SELECT Weekend,
SUM(Total) AS Sales
FROM Cleaned_ecommerce_sales
GROUP BY Weekend; #Weekend sales compare karta yetay

# Price category
SELECT Price_category,
COUNT(*) AS Products
FROM Cleaned_ecommerce_sales
GROUP BY Price_category; #Low,Medium,High price product distribution

#order size
SELECT Order_size,
COUNT(*) AS Orders
FROM Cleaned_ecommerce_sales
GROUP BY Order_size; #large vs small orders

# Highest Profit Product
SELECT Product,
SUM(Profit) AS Profit
FROM cleaned_ecommerce_sales
GROUP BY Product
ORDER BY Profit DESC
LIMIT 5; #Most profitable products.

#Highest Spending Customer
SELECT Customer_Name,
SUM(Total) AS Spending
FROM cleaned_ecommerce_sales
GROUP BY Customer_Name
ORDER BY Spending DESC
LIMIT 10; #Top customers identify hotat.

#Top Months
SELECT Month,
SUM(Profit) AS Profit
FROM cleaned_ecommerce_sales
GROUP BY Month
ORDER BY Profit DESC; #Most profitable month.

#Category + Profit
SELECT
Category,
SUM(Profit) AS Profit
FROM cleaned_ecommerce_sales
GROUP BY Category
ORDER BY Profit DESC;

#Payment + Revenue
SELECT
Payment_Method,
SUM(Total) AS Revenue
FROM cleaned_ecommerce_sales
GROUP BY Payment_Method;

#Final Dashboard Query
SELECT
COUNT(*) Total_Orders,
SUM(Total) Total_Revenue,
SUM(Profit) Total_Profit,
AVG(Total) Average_Order_Value
FROM cleaned_ecommerce_sales;

# Stored Procedures
#Instead of writing the same SQL repeatedly, store it once.
DELIMITER //

CREATE PROCEDURE GetTopProducts()
BEGIN

SELECT
Product,
SUM(Total) AS Sales
FROM cleaned_ecommerce_sales
GROUP BY Product
ORDER BY Sales DESC;

END //

DELIMITER ;
CALL GetTopProducts();

DELIMITER //

CREATE PROCEDURE GetCategorySales()
BEGIN

SELECT
Category,
SUM(Total) AS Sales
FROM cleaned_ecommerce_sales
GROUP BY Category;

END //

DELIMITER ;
CALL GetCategorySales();








